//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentManager.Common.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RentManager.Common.Constants.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BTSave {
            get {
                return ResourceManager.GetString("BTSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Bill.
        /// </summary>
        public static string FTElectricBillSection {
            get {
                return ResourceManager.GetString("FTElectricBillSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests.
        /// </summary>
        public static string FTGuestSection {
            get {
                return ResourceManager.GetString("FTGuestSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string FTRentSection {
            get {
                return ResourceManager.GetString("FTRentSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Billed Amount.
        /// </summary>
        public static string LTBilledAmount {
            get {
                return ResourceManager.GetString("LTBilledAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Billed Units.
        /// </summary>
        public static string LTBilledUnits {
            get {
                return ResourceManager.GetString("LTBilledUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Meter Unit.
        /// </summary>
        public static string LTCurrentUnits {
            get {
                return ResourceManager.GetString("LTCurrentUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Address.
        /// </summary>
        public static string LTGuestAddress {
            get {
                return ResourceManager.GetString("LTGuestAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document ID.
        /// </summary>
        public static string LTGuestDocId {
            get {
                return ResourceManager.GetString("LTGuestDocId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string LTGuestDocType {
            get {
                return ResourceManager.GetString("LTGuestDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Email.
        /// </summary>
        public static string LTGuestEmail {
            get {
                return ResourceManager.GetString("LTGuestEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Name.
        /// </summary>
        public static string LTGuestName {
            get {
                return ResourceManager.GetString("LTGuestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Phone.
        /// </summary>
        public static string LTGuestPhone {
            get {
                return ResourceManager.GetString("LTGuestPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Meter Billed Units.
        /// </summary>
        public static string LTLastBilled {
            get {
                return ResourceManager.GetString("LTLastBilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Per Unit.
        /// </summary>
        public static string LTPricePerUnit {
            get {
                return ResourceManager.GetString("LTPricePerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select guest account.
        /// </summary>
        public static string LTSelectGuest {
            get {
                return ResourceManager.GetString("LTSelectGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Bill for the month.
        /// </summary>
        public static string LTSelectMonth {
            get {
                return ResourceManager.GetString("LTSelectMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Bill Cycle Start Date.
        /// </summary>
        public static string LTSelectStartMonth {
            get {
                return ResourceManager.GetString("LTSelectStartMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Bill Cycle End Date.
        /// </summary>
        public static string LTSelectStopMonth {
            get {
                return ResourceManager.GetString("LTSelectStopMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Billed Amount.
        /// </summary>
        public static string PHBilledAmount {
            get {
                return ResourceManager.GetString("PHBilledAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Billed Units.
        /// </summary>
        public static string PHBilledUnits {
            get {
                return ResourceManager.GetString("PHBilledUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Current Meter Units.
        /// </summary>
        public static string PHCurrentUnits {
            get {
                return ResourceManager.GetString("PHCurrentUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Address.
        /// </summary>
        public static string PHGuestAddress {
            get {
                return ResourceManager.GetString("PHGuestAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Document ID.
        /// </summary>
        public static string PHGuestDoc {
            get {
                return ResourceManager.GetString("PHGuestDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Document Type.
        /// </summary>
        public static string PHGuestDocType {
            get {
                return ResourceManager.GetString("PHGuestDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email.
        /// </summary>
        public static string PHGuestEmail {
            get {
                return ResourceManager.GetString("PHGuestEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name.
        /// </summary>
        public static string PHGuestName {
            get {
                return ResourceManager.GetString("PHGuestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Phone.
        /// </summary>
        public static string PHGuestPhone {
            get {
                return ResourceManager.GetString("PHGuestPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Last Meter Billed Units.
        /// </summary>
        public static string PHLastBilled {
            get {
                return ResourceManager.GetString("PHLastBilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Price Per Units.
        /// </summary>
        public static string PHPricePerUnits {
            get {
                return ResourceManager.GetString("PHPricePerUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bill.
        /// </summary>
        public static string PTAddBill {
            get {
                return ResourceManager.GetString("PTAddBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Guest.
        /// </summary>
        public static string PTAddGuest {
            get {
                return ResourceManager.GetString("PTAddGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Electricity Bill.
        /// </summary>
        public static string PTViewElectricBill {
            get {
                return ResourceManager.GetString("PTViewElectricBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Guests.
        /// </summary>
        public static string PTViewGuest {
            get {
                return ResourceManager.GetString("PTViewGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the guest..
        /// </summary>
        public static string TMGuestSavedFailed {
            get {
                return ResourceManager.GetString("TMGuestSavedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest saved successfully..
        /// </summary>
        public static string TMGuestSavedPassed {
            get {
                return ResourceManager.GetString("TMGuestSavedPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Guest record found, please Add Guest records..
        /// </summary>
        public static string TMNoGuestFound {
            get {
                return ResourceManager.GetString("TMNoGuestFound", resourceCulture);
            }
        }
    }
}
